### ISSUE TITLE
Step east/west not working with diseqc12

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#11]
Trying to move a step in either direction the dialog pops out with a message:
Rotor control setting ROTOR_MASTER_DISEQC12 does not allow moving the positioner

As a workaround i added pychdb.rotor_control_t.ROTOR_MASTER_DISEQC12 at L811 of /gui/neumodvb/positioner_dialog.py

Step moving now works with diseqc12 but i'm not sure if it breaks something else. Would be also useful to be able to specify number of steps to move (i think max limit is 128)

**Comment by deeptho** [comment]
The correct fix is the following. It s time that I upload a new version, because this was fixed locally. Maybe this weekend.

       if self.lnb.rotor_control in (pychdb.rotor_control_t.ROTOR_MASTER_DISEQC12,
                                      pychdb.rotor_control_t.ROTOR_MASTER_USALS):
