### ISSUE TITLE
BUG: tune transponder below 1000ks/s

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#12]
In /src/receiver/frontend.cc at line 1076 there is check that force blindscan if sr<1000 and it prevents regular tuning.
At the same line there is also check for auto delivery system that is preventing use of auto delivery system when trying to make it work in regular tuning mode. Can you rework this somehow if removing delsys check breaks things for other drivers?

**Comment by deeptho** [comment]
You culd replace that line with:

```
	auto blindscan = tune_options.use_blind_tune || mux.delivery_system == chdb::fe_delsys_dvbs_t::SYS_AUTO
		|| (mux.symbol_rate < 1000000 &&  ts.readAccess()->dbfe.supports.blindscan);
```

That will disable the blindscan when not requested.  
I will include it in a future version (unless there are problems)

**Comment by psyborg55** [comment]
I think this is a bit redundant, unless there is a need to have blindscan running whenever sr is lower than 1000 regardless of the requested tuning algo...
I removed that condition and tuning 890ks transponder works.
Also if the dbfe.supports.blindscan is what determines blindscan feature in frontend section of UI, the modification you suggested would not yield any result.

Also removed
mux.delivery_system == chdb::fe_delsys_dvbs_t::SYS_AUTO
condition, changed SYS_AUTO defines from 0 to 22 (dvb_frontend.c says that old apps send 0 as a delsys request, which is SYS_UNDEFINED, and since neumo is a new app i think it should rely on new style), made some modifications to HW algo driver found in coreelec tree, and i got it to tune both DVBS and DVBS2 transponder when setting SYS_AUTO for both. There is one caveat: need to send tune request twice for successfull lock.
Also tried to port changes to SW algo driver but there it didnt work (looks like problems with status reading)

**Comment by deeptho** [comment]
It is important to enable blindscan at low symbol rates. Otherwise tuning will fail for many
users in many cases.

And no, I do not think it is redudant to let people still choose to not use blindscan. After all, this is also what you asked.

**Comment by psyborg55** [comment]
Ok, that was fair explanation.
Assuming dbfe.supports.blindscan is not used to determine frontend capability in GUI?
If not is it fine to modify delsys condition check in the same way?

**Comment by psyborg55** [comment]
After bulding latest version i noticed this does not work. Why and how did it work once i have no idea
