### ISSUE TITLE
overlay stats range

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#15]
When the signal is very strong overlay will not display correct values

![Screenshot from 2022-05-03 10-54-18](https://user-images.githubusercontent.com/15853469/166553594-7f1496bf-5312-40e9-9bea-2adfe7ccec30.png)

**Comment by deeptho** [comment]
This is not what I get (CCM). It seems you are running an old version of neumodvb.
Also: this info is determined at lock time. It could be a temporary problem.

**Comment by psyborg55** [comment]
Old version is not a problem. It happens in https://github.com/deeptho/neumodvb/commit/2b6f4ead132dc48f65a0a54f7f1f7adc3e53ba06 too. Incorrect info was present all the time since i started working with neumodvb

**Comment by deeptho** [comment]
Should be fixed and/or happens on non-blindscan supporting drivers

**Comment by psyborg55** [comment]
Not by itself. https://github.com/deeptho/neumodvb/pull/23
