### ISSUE TITLE
incorrect stream type indication

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#18]
in positioner dialog there is ACM/VCM indication highlight for all streams (CCM)
see screenshot in https://github.com/deeptho/neumodvb/issues/15

**Comment by deeptho** [comment]
Should be fixed now and/or occurs because of non-blindscan-supporting driver

**Comment by psyborg55** [comment]
still there
![Screenshot from 2022-08-13 01-12-08](https://user-images.githubusercontent.com/15853469/184446586-05e186f5-4c0d-4b95-9fca-21a81d45cb5b.png)

**Comment by deeptho** [comment]
Which card is this? m88rs6060 has some missing features. Of course it could be a bug, but
on stid135 it is correct. You can check /var/log/debug to find some clues about what might be wrong.
Specifically the matype value seems to be wrong. Or perhaps you are using outdated versions of software
![x](https://user-images.githubusercontent.com/1910568/184717660-d518cb7b-de80-4984-8348-64284d92800b.png)

**Comment by psyborg55** [comment]
still m88ds3103. latest revision built yesterday, and latest drivers as well. did you check other cards like stv or tas2101?
if it is driver problem i'll look into that, its just i thought more likely a neumodvb problem

**Comment by deeptho** [comment]
I do not have time to check all cards all the time and each time I do there are problems to be found. 

I would advise first to see what matype NUMBER the drivers return to user space. The idea is to use this as 
the "normative" value. Usually this is read from the stream. In some cases I had to reconstruct it (in the drivers)
from other pieces of information. I usually trust the value of tbs6909x most

Note that from time to time the cards return wrong information. It is rare though
