### ISSUE TITLE
support non-blindscan drivers

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#19]
attempt to tune with nonblindscan driver will result in failure with
dtv_property_process_set: SET cmd 0x0000004a undefined
message in log, as well as dtv_property_process_set: SET cmd 0x0000004d undefined message once the 4a is bypassed

This is because the commands 4a and 4d do not exist in mainline, one of them is PLS related, cant remember what the other is for.

if set to check and send these commands only if blindscan driver is found, then mainline nonblindscan driver can be used with neumodvb without problems

**Comment by deeptho** [comment]
Should be ok now

**Comment by psyborg55** [comment]
latest neumodvb revision + 5.13.0-19 kernel it is still the same

**Comment by psyborg55** [comment]
just needed this https://github.com/psyborg55/neumodvb/commit/794cfe8bafa0fe7d2f693a0cac1986843e5e1233

**Comment by deeptho** [comment]
Merged
