### ISSUE TITLE
Specific positioner issue with dual output LNB

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#21]
I have here wideband LNB from inverto, tested for a while so far and for the most part it works. It tunes both H and V pol transponders accross entire spectrum (some SNR problems at band edges, expected due to tuner capabilites, cabling and switch specification)

Problem appears when trying to use rotor attached through 19V port cable.
After a while of use (at first the rotating works) rotor goes deaf and doesnot respond to commands to drive dish.
Last time i tested this, after rebooting into windows it didnt accept commands from the windows app too.
So it looks like hardware misconfiguration sometime during use.
What helped for a moment was to disconnect the LNB from the rotor, and driving the dish started to work immediately without further problems, until the LNB was connected again.
After tuning transponder and making fine dish adjustment, on next attempt to rotate it, rotor went deaf again.

I also tried to connect the rotor through 13V port and in this case it would not move dish at all, no matter what.

Am i running into design limitation here, or there is bug somewhere in the software causing this type of behavior? 

All devices are connected using voltage controled switch, in the screenshots D0A0 (upper window) is old pctv461e, D0A1 (middle) and D0A2 (bottom) are newer wintv devices. New devices seem to do better at high part of the band, but worse in lower part of the band. With the setup any device can tune any of the transponders regardless of polarity or other devices status.
![Screenshot from 2022-07-15 18-53-35](https://user-images.githubusercontent.com/15853469/179255297-ecddc532-fe58-40ad-b340-252f1a8b3c9b.png)
![Screenshot from 2022-07-15 18-54-23](https://user-images.githubusercontent.com/15853469/179255315-9162bdc1-ac69-47c6-95b0-96aa72440261.png)
![Screenshot from 2022-07-15 18-56-26](https://user-images.githubusercontent.com/15853469/179255328-42cec9bd-33fc-47e9-832b-04d082a6ea0e.png)
![Screenshot from 2022-07-15 19-01-01](https://user-images.githubusercontent.com/15853469/179255336-16586962-0af6-46b3-9b37-79d960f99776.png)

**Comment by deeptho** [comment]
I think the problem might be in the code that I copied from you. The code thinks always that the high band is being 
used and then transmits 22khz, which might confuse the lnb (not sure).

Try changing ub chdb_extra.cc:
freq_mid = freq_low;
into 
freq_mid = freq_high;
in the entries for lnb_type_t::WDBUK and lnb_type_t::WDB
and see if it helps.

By the way: why is there a need for both  lnb_type_t::WDBUK and lnb_type_t::WDB?

**Comment by psyborg55** [comment]
Thanks. I'll take a closer look at that.
I didn't need both WDB types, as i don't have UK version, but some other user might have it and since the concept is the same proper support of one variant will be valid for another too. Difference in the UK as far as i know is the sky and freesat use 10.41 ghz LO, while EU variant use 10.40

**Comment by deeptho** [comment]
Then it is indeed best to have two variants. Saves the user changing the default value

**Comment by psyborg55** [comment]
with freq_mid = freq_high; there are no more SET_TONE messages in log when trying to drive the dish
driving with each of the LNB ports connected to rotor is working, and both polariazations can drive it at high (19V) or low (13V) speed. it was just the configuration problem. needed to select VH type for driving at vertical pol
why this matters and how to simplify the config?

**Comment by psyborg55** [comment]
in the end, rotor has just one port and both cables will never connect to it at the same time so it doesn't matter why this strange design with inverted polarization. as long as it can rotate regardless of polarization cable attached through it all is good.
