### ISSUE TITLE
neumoplot detrend bug

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#22]
in https://github.com/deeptho/neumodvb/blob/master/gui/neumodvb/neumoplot.py#L386

has_two_bands = (highest_freq > 11700+8) and (lowest_freq < 11700-8)

always assumes there are two bands. can you make it depend on lnb_type, something like

has_two_bands = lnb_type_t::UNIV

current code doesnt look good with wideband LNB, see screenshots
![Screenshot from 2022-08-05 21-39-16](https://user-images.githubusercontent.com/15853469/183113561-0d8f797a-98d8-4aaa-9583-b0fdde2b9b23.png)

after detrend code removed:

![Screenshot from 2022-08-05 21-40-47](https://user-images.githubusercontent.com/15853469/183113650-77454e5b-63d8-423f-86e3-60961853c1f5.png)

**Comment by deeptho** [comment]
Your proposed fix is not enough, as the detrending must know if there are actually two bands in the file. Even
with Universal lNB you can decide to scan only part of the spectrum.
You could try instead:
        has_two_bands = (highest_freq > 11700+8) and (lowest_freq < 11700-8) and \
            self.spectrum.k.lnb_key.dish_id.lnb_type == pychdb.lnb_type.UNIV

What card are you  using? Most tuners support only 1 Ghz of bandwidt, so they would not be able to capture
the highest part of the band.

**Comment by psyborg55** [comment]
> Even
> with Universal lNB you can decide to scan only part of the spectrum.

then that part is stored in signle databse file, and would not be combined with other scan result, or?

pctv461/ wintv novas2

**Comment by deeptho** [comment]
Not sure what you are asking. The config is indeed stored in the database and will work for all spectra
if the info is correct

**Comment by psyborg55** [comment]
self.spectrum.k.lnb_key.dish_id.lnb_type == pychdb.lnb_type.UNIV 
ends up in
AttributeError: 'int' object has no attribute 'lnb_type'

latest version also doesn build:
CMake Error: The source directory "/home/tom/nm" does not appear to contain CMakeLists.txt.

**Comment by deeptho** [comment]
Corrected:
        has_two_bands = (highest_freq > 11700+8) and (lowest_freq < 11700-8) and \
            self.spectrum.k.lnb_key.lnb_type == pychdb.lnb_type_t.UNIV

**Comment by psyborg55** [comment]
Now
AttributeError: module 'pychdb' has no attribute 'lnb_type'

**Comment by deeptho** [comment]
That is why it is lnb_type_t and not lnb_type

**Comment by psyborg55** [comment]
Ok.it works. lnb_type_t is stored into db for every scan also?
While testing i tried to modify LNB type of current interface but this looked wrong as it made no difference

**Comment by deeptho** [comment]
Yes, it is stored in the db but not very important uinless you have multiple lnbs (C/Ku) for the same satellite on the same dish
