### ISSUE TITLE
Ubuntu 23.04 packages missing

### ISSUE THREAD

**Issue by elkizana** [deeptho/neumodvb#30]
![Screenshot from 2023-05-15 18-06-39](https://github.com/deeptho/neumodvb/assets/53874333/82d3271a-9679-420e-a690-1061b254a32f)

**Comment by deeptho** [comment]
Please do not post bitmaps.
If you have a description of how to install on ubuntu 23.0 then create a pull request with updated documentation or provide the install command.

**Comment by andimik** [comment]
In case other people want to search for the same issue, I have converted the picture into text

```
idoomgdoom: $ sudo apt install -y libboost-all-dev libgtk-3-0 libgtk-3-dev curl libcurl4-openssl-dev libwxgtk-me• ta3.0-gtk3-dey gettext libextf-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev python3-configobj python3-cachet. ols python3-jinja2 python3-pip clang-format python3-sip-dev libconfig-dev libconfigoo-dev libdvbcsa-dev libmpv-dev freeglut3-dev libwxgtk3.0-gtk3-dey python3-wxgtk-media4.0 python3-wxgtk-webview4.0 python3-wxgtk4.0 python3-scipy clang lsb-core lsb-release py. Ih'n3-regex liblog4cxx12 liblog4cxx-dev freeglut3 
Reading package lists... Done 
Building dependency tree... Done 
Reading state information... Done 

Package lsb-core is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source 

E: Unable to locate package libwxgtk-media3.0-gtk3-dev 
E: Couldn't find any package by glob 'libwxgtk-media3.0-gtk3-dev. 
E: Unable to locate package libwxgtk3.0-gtk3-dev 
E: Couldn't find any package by glob 'libwxgtk3.0-gtk3-dev. 
E: Package 'lsb-core. has no installation candidate 
E: Unable to locate package liblog4cxx12 
E: Unable to locate package freeglut3 
idoomgdoom:-/neumodvb/build$ 
```

**Comment by elkizana** [comment]
`sudo apt install -y libboost-all-dev libgtk-3-0 libgtk-3-dev curl libcurl4-openssl-dev  libwxgtk-media3.0-gtk3-dev gettext libexif-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev   python3-configobj python3-cachetools python3-jinja2 python3-pip clang-format python3-sip-dev libconfig-dev libconfig++-dev libdvbcsa-dev  libmpv-dev freeglut3-dev libwxgtk3.0-gtk3-dev python3-wxgtk-media4.0 python3-wxgtk-webview4.0 python3-wxgtk4.0 python3-scipy clang lsb-core lsb-release python3-regex liblog4cxx12 liblog4cxx-dev freeglut3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package lsb-core is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libwxgtk-media3.0-gtk3-dev
E: Couldn't find any package by glob 'libwxgtk-media3.0-gtk3-dev'
E: Unable to locate package libwxgtk3.0-gtk3-dev
E: Couldn't find any package by glob 'libwxgtk3.0-gtk3-dev'
E: Package 'lsb-core' has no installation candidate
E: Unable to locate package liblog4cxx12
E: Unable to locate package freeglut3
`

**Comment by elkizana** [comment]
Solved by adding Ubuntu 22.04 repos

**Comment by andimik** [comment]
@elkizana 

Please write down how you did that.

**Comment by elkizana** [comment]
added Ubuntu 22.04 repositories to /etc/apt/sources.list 
Here they are : 

deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
deb http://archive.canonical.com/ubuntu/ jammy partner


Then installed the required packages mentioned in the readme
