### ISSUE TITLE
Segfault when trying to view a channel using CTRL+Enter

### ISSUE THREAD

**Issue by rylecqfd** [deeptho/neumodvb#33]
Hi

I'm using Fedora 38 under a VM in Promox with a TBS 6904SE running in PCIE passhtrough. 
The virtual graphic card is SPICE/QXL.
I managed to freshly compile (and use) the blindscan drivers and neumodvb following the instructions, but I get this error message if  I simply try to run neumodvb (and pretty much nothing works in the menus):

![image](https://github.com/deeptho/neumodvb/assets/37713285/6dd63bd0-e97c-496c-983d-2bba651eb453)

If I launch neumodvb with GDK_BACKEND=x11, I can use most of the program: add LNBs, satellites, get Spectrum, run blindscan ... but when I want to view a channel with CTRL+Enter, I get a segmentation fault.

Here is the neumodvb log for such a crash:
[neumo.zip](https://github.com/deeptho/neumodvb/files/12031270/neumo.zip)

Is there something I missed ?

(Once a frequency is tuned through neumodvb, it seems that the data comes OK through the card as I can for example use dvbstream 8192 -o | vlc - to view the channels).

**Comment by rylecqfd** [comment]
For the Wayland / EGL issue, I found this post: https://www.satellites.co.uk/forums/threads/neumodvb.179577/page-40#post-1145675 and switched the default GNOME session following https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/.

I still have the crash while trying to view a channel using CTRL+Enter though.

**Comment by deeptho** [comment]
When neumodvb crashes, there are no useful messages in the log files. You should at least report the messages
on the console and best use gdb to figire out where it crashes

**Comment by rylecqfd** [comment]
Hi
As stated on the satellites.co.uk [thread](https://www.satellites.co.uk/forums/threads/neumodvb.179577/page-45), I don't have this crash anymore since I added a `#` in front of the `$<$<CONFIG:DEBUG>:-Og>` line in the CmakeLists.txt like you told me to do before being able to try to debug neumodvb using gdb.

The only crash that stays is the one I get when trying to add a PiP window using CTRL+SHIFT+Enter.
A crash that you're linking to a MESA bug if I understand correctly.

**Comment by deeptho** [comment]
THen it is probably a bug with the "fibers" code, which may have been fixed in the newer (not yet released) versions.
So try a new version when it becomes available (in a few weeks time).

The mesa bug is a nasty one: there has been no response from upstream. In the mean time mesa has changed so much that even my workaround no longer worked, but I found  new one.

**Comment by deeptho** [comment]
Probably fixed. Reopen if not.
