### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by fahadwest** [deeptho/neumodvb#34]
hello i have a problem when i try to cmake the build it gives me error 

im using ubuntu 22.04

z7labs@dvb:~/neumodvb/build$ cmake ..
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/z7labs/neumodvb/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_012f0/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_012f0.dir/build.make CMakeFiles/cmTC_012f0.dir/build
    gmake[1]: Entering directory '/home/z7labs/neumodvb/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_012f0.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++    -MD -MT CMakeFiles/cmTC_012f0.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_012f0.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_012f0.dir/testCXXCompiler.cxx.o -c /home/z7labs/neumodvb/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_012f0
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_012f0.dir/link.txt --verbose=1
    /usr/bin/clang++  -Wl,-z,defs -Wl,--no-undefined -fuse-ld=gold  CMakeFiles/cmTC_012f0.dir/testCXXCompiler.cxx.o -o cmTC_012f0
    /usr/bin/ld.gold: error: cannot find -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_012f0.dir/build.make:100: cmTC_012f0] Error 1
    gmake[1]: Leaving directory '/home/z7labs/neumodvb/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_012f0/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)

**Comment by deeptho** [comment]
So this is unrelated to neumodvb.

**Comment by andimik** [comment]
https://github.com/deeptho/blindscan/issues/2

This will help you. Indeed this is an issue, so I don't understand why it has been closed.
