### ISSUE TITLE
Building on 22.04 w/ additional steps to compile 

### ISSUE THREAD

**Issue by alphafox02** [deeptho/neumodvb#38]
https://github.com/alphafox02/neumodvb/blob/master/docs/INSTALL.md?plain=1

Feel free to review, but it would appear there’s no need for 23.10/24.04, unless there’s something I’m missing. Someone else has also confirmed the steps and managed to get a successful lock on satellite.

**Comment by deeptho** [comment]
I will add the instructions in the next version.

**Comment by alphafox02** [comment]
Thank you. Do you know if libcurl4-openssl-dev is needed in place of libcurl4-gnutls-dev? Reason I ask is that DragonOS FocalX has libcurl4-gnutls-dev in it by default for some other project I believe. It's been awhile so I can't remember. Your package list includes libcurl4-openssl-dev and a couple packages that need it, but after installing them it complains some existing packages need libcurl4-gnutls-dev. So after I run apt install on your list I reinstall libcurl4-gnutls-dev and of course some other packages complain it needs libcurl4-gnutls-dev but everything seems to run fine after I put libcurl4-gnutls-dev back in place.

Just got me thinking if libcurl4-gnutls-dev is okay in the first place.

**Comment by alphafox02** [comment]
I changed the apt install to libcurl4-gnutls-dev and all still builds fine. I did have an issue with a timeout on the wget so people need to pay attention there.
