### ISSUE TITLE
Archlinux: sip.h issue

### ISSUE THREAD

**Issue by ilikenwf** [deeptho/neumodvb#41]
I have all the deps installed and am working on a PKGBUILD for the AUR. For whatever reason, this is breaking for me:

wxpy_api.h:18:10: fatal error: 'sip.h' file not found

But... 

/usr/lib/python3.12/site-packages/wx/include/wxPython/sip.h exists.

Any suggestions?

What's odd is none of the other files using sip.h are breaking, just this one.

**Comment by deeptho** [comment]
I am not familiar with arch linux.
In fedora40, sip.h is here:
/usr/include/python3.12/sip.h

**Comment by ilikenwf** [comment]
Interesting...

I'll keep digging; I tried adding the path to the includes in my cmake command without luck. 

I did get your kernel drivers working by using a PKGBUILD for the official TBS ones. There's a DKMS version I'd like to get going sometime, but DKMS is a pain in the butt to work with.

With Arch, they usually install python libs in the site-packages directory systemwide, similar to how pip as root would is all. I'm surprised that cmake's Find for python and friends isn't including that path already...

Here's an example of the current PKGBUILD i'm working on for Neumo, they're just structured, standardized, glorified bash scripts that pacakge the given software:

```
# Maintainer: Your Name <youremail@domain.com>
pkgname=neumodvb
pkgver=1.0.0
pkgrel=1
pkgdesc="NeumoDVB is software to interact with DVB devices"
arch=('x86_64')
url="https://github.com/deeptho/neumodvb"
license=('GPL')
depends=('cmake' 'uuid' 'clang' 'libtool' 'boost-libs' 'curl' 'log4cxx' 'libconfig' 'wxgtk3' 
         'gtk3' 'freeglut' 'librsvg' 'libexif' 'gobject-introspection' 'expat' 'python-wxpython' 
         'python-jinja' 'python-matplotlib' 'python-scipy' 'python-pyqt6-sip' 'python-cachetools' 
         'python-gobject' 'python-configobj' 'libx11' 'libglvnd' 'espeak' 'mesa' 'mpv' 'libdvbcsa' 
         'ffmpeg' 'fmt' 'python-mpl-scatter-density')
makedepends=('git' 'boost' 'tsduck' 'ccache')
optdepends=('mate-desktop: A desktop environment to run NeumoDVB on X11')
source=("git+https://github.com/deeptho/neumodvb.git")
md5sums=('SKIP')

prepare() {
    cd "$srcdir/neumodvb"
    # Any additional patching or preparation can go here
}

build() {
    cd "$srcdir/neumodvb"
    mkdir -p build
    cd build
    cmake -DCMAKE_INCLUDE_PATH=/usr/lib/python3.12/site-packages/wx/include/wxPython ..
    make -j$(nproc)
}

package() {
    cd "$srcdir/neumodvb/build"
    make DESTDIR="$pkgdir" install
}

# Optional: Handle ccache setup for faster rebuilds, if user has ccache enabled
ccache_setup() {
    export CC="ccache clang"
    export CXX="ccache clang++"
}

```

**Comment by ilikenwf** [comment]
Which sip package is it from the pip standpoint you're using - the wxwidgets/pygtk one, or just python-sip?

**Comment by ilikenwf** [comment]
@deeptho what version of sip are you using? Apparently some of the structure has changed for sip6...I had to install sip4.

**Comment by ilikenwf** [comment]
So I haven't had a chance to actually make sure it all works yet but it does build now. Here's the Archlinux PKGBUILD in case you want to add it to your readme:

https://aur.archlinux.org/packages/neumodvb-git

I haven't even checked yet to see if it is already including a .desktop file yet...ha!

**Comment by deeptho** [comment]
After you sure everything works, I can add the build information for archlinux to the documentation. In case you are planning to keep your git uptodate I can add a link as well.

**Comment by ilikenwf** [comment]
I have to determine if what I'm hitting the wall with now when running is a "me" issue or something I need to fix for the package, but once that's done and I get it configured I should be able to actually test it.

The -git packages are nice because they always build whatever is latest in your git repo.
